/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import java.awt.event.ActionListener;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import Controller.AdRoomRegistrationController;
import Model.AdRoomRegistrationModel;
import OptionPaneUI.ByIDFieldEmpty;
import OptionPaneUI.DeletedSuccessfully;
import OptionPaneUI.FieldsEmpty;
import OptionPaneUI.RegisteredSuccessfully;
import OptionPaneUI.UpdatedSuccessfully;
import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author anukul
 */
public class AdminRoomRegistrationView extends javax.swing.JFrame {
    AdRoomRegistrationModel adModel;
    /**
     * Creates new form AdminRoomRegistrationView
     */
    public AdminRoomRegistrationView() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        ViewTable.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 16));
        ViewTable.getTableHeader().setOpaque(false);
        ViewTable.getTableHeader().setForeground(new Color(44,107,120));
    }
    public AdRoomRegistrationModel getData() {
        adModel = new AdRoomRegistrationModel(roomNoTxt.getText(),roomChargeTxt.getText());
        return adModel;
    }
     public AdRoomRegistrationModel getDataUpdate() {
        adModel = new AdRoomRegistrationModel(roomIdTxt.getText(),roomNoTxt.getText(),roomChargeTxt.getText());
        return adModel;
    }

    public AdRoomRegistrationModel getDataDelete() {
        adModel = new AdRoomRegistrationModel(roomIdTxt.getText());
        return adModel;
    }
    public AdRoomRegistrationModel getDataView(){
        adModel = new AdRoomRegistrationModel(roomIdTxt.getText(),roomNoTxt.getText(),roomChargeTxt.getText());
        return adModel;
    }
    public void deleteRoomsListener(ActionListener log) {
        DeleteButton.addActionListener(log);
    }

    public void addRoomsListener(ActionListener log) {
        RegisterButton.addActionListener(log);
    }
    public void updateRoomsListener(ActionListener log) {
        UpdateButton.addActionListener(log);
    }
    public void viewRoomsListener(ActionListener log){
        ViewButton.addActionListener(log);
    }
    private boolean isEmpty() {
        return roomNoTxt.getText().isEmpty() || roomChargeTxt.getText().isEmpty();
    }
     private boolean isEmptyUpdate() {
        return roomIdTxt.getText().isEmpty()||roomNoTxt.getText().isEmpty() || roomChargeTxt.getText().isEmpty();
    }

    private boolean isEmptyDelete() {
        return roomIdTxt.getText().isEmpty();
    }
    private void resetText(){
        roomIdTxt.setText("");
        roomNoTxt.setText("");
        roomChargeTxt.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.WARNING: Do NOT modify this code.
     * The content of this method is always
 regenerated by the Form Editor.
     * @param log
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        RoomRegistrationLogo = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        RegisterButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        ViewButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        RoomNoLabel = new javax.swing.JLabel();
        roomChargeTxt = new javax.swing.JTextField();
        RoomChargeLabel = new javax.swing.JLabel();
        roomNoTxt = new javax.swing.JTextField();
        ByNumberLabel = new javax.swing.JLabel();
        roomIdTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ViewTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(162, 186, 190));
        jPanel1.setLayout(null);

        RoomRegistrationLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/RoomRegistrationLogo.png"))); // NOI18N
        jPanel1.add(RoomRegistrationLogo);
        RoomRegistrationLogo.setBounds(19, 6, 652, 210);

        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Back.png"))); // NOI18N
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        jPanel1.add(BackButton);
        BackButton.setBounds(937, 33, 187, 90);

        RegisterButton.setBackground(new java.awt.Color(24, 85, 98));
        RegisterButton.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        RegisterButton.setForeground(new java.awt.Color(255, 255, 255));
        RegisterButton.setText("REGISTER");
        RegisterButton.setBorder(null);
        RegisterButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });
        jPanel1.add(RegisterButton);
        RegisterButton.setBounds(100, 470, 170, 55);

        UpdateButton.setBackground(new java.awt.Color(24, 85, 98));
        UpdateButton.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        UpdateButton.setForeground(new java.awt.Color(255, 255, 255));
        UpdateButton.setText("UPDATE");
        UpdateButton.setBorder(null);
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });
        jPanel1.add(UpdateButton);
        UpdateButton.setBounds(300, 470, 157, 55);

        ViewButton.setBackground(new java.awt.Color(24, 85, 98));
        ViewButton.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        ViewButton.setForeground(new java.awt.Color(255, 255, 255));
        ViewButton.setText("VIEW");
        ViewButton.setBorder(null);
        ViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ViewButton);
        ViewButton.setBounds(310, 660, 128, 43);

        DeleteButton.setBackground(new java.awt.Color(24, 85, 98));
        DeleteButton.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        DeleteButton.setForeground(new java.awt.Color(255, 255, 255));
        DeleteButton.setText("DELETE");
        DeleteButton.setBorder(null);
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });
        jPanel1.add(DeleteButton);
        DeleteButton.setBounds(110, 660, 168, 43);

        RoomNoLabel.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        RoomNoLabel.setText("Room No.");
        jPanel1.add(RoomNoLabel);
        RoomNoLabel.setBounds(40, 310, 135, 41);

        roomChargeTxt.setBackground(new java.awt.Color(174, 200, 204));
        roomChargeTxt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        roomChargeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomChargeTxtActionPerformed(evt);
            }
        });
        jPanel1.add(roomChargeTxt);
        roomChargeTxt.setBounds(260, 390, 222, 38);

        RoomChargeLabel.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        RoomChargeLabel.setText("Room charge");
        jPanel1.add(RoomChargeLabel);
        RoomChargeLabel.setBounds(40, 380, 189, 41);

        roomNoTxt.setBackground(new java.awt.Color(174, 200, 204));
        roomNoTxt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel1.add(roomNoTxt);
        roomNoTxt.setBounds(260, 310, 222, 41);

        ByNumberLabel.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        ByNumberLabel.setText("By ID");
        jPanel1.add(ByNumberLabel);
        ByNumberLabel.setBounds(60, 570, 96, 54);

        roomIdTxt.setBackground(new java.awt.Color(174, 200, 204));
        jPanel1.add(roomIdTxt);
        roomIdTxt.setBounds(190, 570, 311, 45);

        ViewTable.setBackground(new java.awt.Color(174, 200, 204));
        ViewTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Room ID", "Room Number", "Room Charge"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ViewTable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(640, 270, 462, 402);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        AdminDashboard ad = new AdminDashboard();
        ad.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_BackButtonActionPerformed

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
        // TODO add your handling code here:
        AdRoomRegistrationController adControl = new AdRoomRegistrationController();
        adControl.RegisterButtonActionPerformed(this);
        if(isEmpty()){
            FieldsEmpty view = new FieldsEmpty();
            view.setVisible(true);       
        }else {
            RegisteredSuccessfully view = new RegisteredSuccessfully();
            view.setVisible(true);       
            resetText();
        }

    }//GEN-LAST:event_RegisterButtonActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:

        AdRoomRegistrationController adControl = new AdRoomRegistrationController();
        adControl.UpdateButtonActionPerformed(this);

        if(isEmptyUpdate()){
            FieldsEmpty view = new FieldsEmpty();
            view.setVisible(true);       
        }else {
            UpdatedSuccessfully view = new UpdatedSuccessfully();
            view.setVisible(true);
            resetText();
        }


    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void ViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewButtonActionPerformed
        // TODO add your handling code here:
        AdRoomRegistrationController adControl = new AdRoomRegistrationController();
        adControl.ViewButtonActionPerformed(this);        
        resetText();

    }//GEN-LAST:event_ViewButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // TODO add your handling code here:
        AdRoomRegistrationController adControl = new AdRoomRegistrationController();
        adControl.DeleteButtonActionPerformed(this);        
        if(isEmptyDelete()){
            ByIDFieldEmpty view = new ByIDFieldEmpty();
            view.setVisible(true);      
        }else {
            DeletedSuccessfully view = new DeletedSuccessfully();
            view.setVisible(true);    
            resetText();
        }
        
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void roomChargeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomChargeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomChargeTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminRoomRegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminRoomRegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminRoomRegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminRoomRegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminRoomRegistrationView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel ByNumberLabel;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JLabel RoomChargeLabel;
    private javax.swing.JLabel RoomNoLabel;
    private javax.swing.JLabel RoomRegistrationLogo;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JButton ViewButton;
    private javax.swing.JTable ViewTable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField roomChargeTxt;
    private javax.swing.JTextField roomIdTxt;
    private javax.swing.JTextField roomNoTxt;
    // End of variables declaration//GEN-END:variables
}
